version: "2"

networks: 
    default:
        external: 
            name: main

services: 
    testerpc:
        build:
            context: .
        image: testerpc
        container_name: testerpc
        restart: on-failure:4
        ports: 
            - 8080:80
        volumes: 
            - .:/var/www/html
        
        working_dir: /var/www/html
        